# Generated by Django 4.1.2 on 2022-10-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-id"],
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
            },
        ),
    ]
