# Generated by Django 4.1 on 2022-10-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_post_tag_post_tags_alter_tag_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                default=None, to="blog.tag", verbose_name="标签"
            ),
        ),
    ]
