# Generated by Django 4.1 on 2022-10-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(default="", to="blog.tag", verbose_name="标签"),
        ),
    ]
