# Generated by Django 4.1 on 2022-10-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_city_person_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="target",
            field=models.CharField(max_length=100, verbose_name="评论目标"),
        ),
    ]
